### ISSUE TITLE
Wrong header used in popup

### ISSUE THREAD

**Issue by deepika087** [HackerEarth/hackerearth-chrome-extension#2]
When I click the popup of the hacker earth extension. I see that under the heading of "upcoming extension" both ongoing and upcoming challenges are included. 
There headings should be different to clearly differentiate between the upcoming and ongoing challenges.

**Comment by deepika087** [comment]
Submitted the pull request(#3 ) for this issue

**Comment by sreeram-dev** [comment]
#4
